-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 21:48:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema thue_tncn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema thue_tncn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thue_tncn` DEFAULT CHARACTER SET utf8mb3 ;
USE `thue_tncn` ;

-- -----------------------------------------------------
-- Table `thue_tncn`.`nguoinopthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`nguoinopthue` (
  `id` VARCHAR(45) NOT NULL,
  `sogiayto` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `masothue` VARCHAR(255) NULL DEFAULT NULL,
  `tencanhan` VARCHAR(255) NULL DEFAULT NULL,
  `tinh/TP` VARCHAR(255) NULL DEFAULT NULL,
  `coquancapMST` VARCHAR(255) NULL DEFAULT NULL,
  `loaigiayto` VARCHAR(45) NULL DEFAULT NULL,
  `sodienthoai` VARCHAR(12) NULL DEFAULT NULL,
  `gioitinh` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `masothue_UNIQUE` (`masothue` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`dailythue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`dailythue` (
  `idDaiLyThue` VARCHAR(255) NOT NULL,
  `ten` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `diachi` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `quan/huyen` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tinh/TP` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `dienthoai` VARCHAR(14) NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `fax` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `hopdongdailythueso` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `ngaytaohopdong` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idDaiLyThue`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`nhanviendallythue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`nhanviendallythue` (
  `idNhanVienDalLyThue` VARCHAR(255) NOT NULL,
  `dailythue_idDaiLyThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idNhanVienDalLyThue`),
  INDEX `fk_nhanviendallythue_dailythue1_idx` (`dailythue_idDaiLyThue` ASC) VISIBLE,
  CONSTRAINT `fk_nhanviendallythue_dailythue1`
    FOREIGN KEY (`dailythue_idDaiLyThue`)
    REFERENCES `thue_tncn`.`dailythue` (`idDaiLyThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tongcucthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tongcucthue` (
  `idTongCucThue` VARCHAR(255) NOT NULL,
  `ten` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `diachi` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `sdt` VARCHAR(14) NULL DEFAULT NULL,
  PRIMARY KEY (`idTongCucThue`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`bangtonghopnguoiphuthuocdkygiamtrugiacanh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`bangtonghopnguoiphuthuocdkygiamtrugiacanh` (
  `idBangTongHopNguoiPhuThuocDKYGiamTruGiaCanh` VARCHAR(255) NOT NULL,
  `tennguoinopthue` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `masothue` VARCHAR(255) NULL DEFAULT NULL,
  `diachi` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `quan/huyen` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tinh/TP` VARCHAR(255) NULL DEFAULT NULL,
  `fax` VARCHAR(255) NULL DEFAULT NULL,
  `dienthoai` VARCHAR(14) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nguoinopthue_id` VARCHAR(45) NOT NULL,
  `dailythue_idDaiLyThue` VARCHAR(255) NOT NULL,
  `nhanviendallythue_idNhanVienDalLyThue` VARCHAR(255) NOT NULL,
  `tongcucthue_idTongCucThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idBangTongHopNguoiPhuThuocDKYGiamTruGiaCanh`),
  INDEX `fk_bangtonghopnguoiphuthuocdkygiamtrugiacanh_nguoinopthue1_idx` (`nguoinopthue_id` ASC) VISIBLE,
  INDEX `fk_bangtonghopnguoiphuthuocdkygiamtrugiacanh_dailythue1_idx` (`dailythue_idDaiLyThue` ASC) VISIBLE,
  INDEX `fk_bangtonghopnguoiphuthuocdkygiamtrugiacanh_nhanviendallyt_idx` (`nhanviendallythue_idNhanVienDalLyThue` ASC) VISIBLE,
  INDEX `fk_bangtonghopnguoiphuthuocdkygiamtrugiacanh_tongcucthue1_idx` (`tongcucthue_idTongCucThue` ASC) VISIBLE,
  CONSTRAINT `fk_bangtonghopnguoiphuthuocdkygiamtrugiacanh_nguoinopthue1`
    FOREIGN KEY (`nguoinopthue_id`)
    REFERENCES `thue_tncn`.`nguoinopthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bangtonghopnguoiphuthuocdkygiamtrugiacanh_dailythue1`
    FOREIGN KEY (`dailythue_idDaiLyThue`)
    REFERENCES `thue_tncn`.`dailythue` (`idDaiLyThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bangtonghopnguoiphuthuocdkygiamtrugiacanh_nhanviendallythue1`
    FOREIGN KEY (`nhanviendallythue_idNhanVienDalLyThue`)
    REFERENCES `thue_tncn`.`nhanviendallythue` (`idNhanVienDalLyThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bangtonghopnguoiphuthuocdkygiamtrugiacanh_tongcucthue1`
    FOREIGN KEY (`tongcucthue_idTongCucThue`)
    REFERENCES `thue_tncn`.`tongcucthue` (`idTongCucThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`cauhinh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`cauhinh` (
  `idCauHinh` VARCHAR(255) NOT NULL,
  `tongcucthue_idTongCucThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCauHinh`),
  INDEX `fk_cauhinh_tongcucthue1_idx` (`tongcucthue_idTongCucThue` ASC) VISIBLE,
  CONSTRAINT `fk_cauhinh_tongcucthue1`
    FOREIGN KEY (`tongcucthue_idTongCucThue`)
    REFERENCES `thue_tncn`.`tongcucthue` (`idTongCucThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`bieuthueluytientungphan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`bieuthueluytientungphan` (
  `idBieuThueLuyTienTungPhan` VARCHAR(255) NOT NULL,
  `bacthue` INT NULL DEFAULT NULL,
  `phanthunhaptinhthuenam` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `phanthunhaptinhthuethang` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `thuesuat` DOUBLE NULL DEFAULT NULL,
  `cauhinh_idCauHinh` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idBieuThueLuyTienTungPhan`),
  INDEX `fk_bieuthueluytientungphan_cauhinh1_idx` (`cauhinh_idCauHinh` ASC) VISIBLE,
  CONSTRAINT `fk_bieuthueluytientungphan_cauhinh1`
    FOREIGN KEY (`cauhinh_idCauHinh`)
    REFERENCES `thue_tncn`.`cauhinh` (`idCauHinh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`bieuthuetoanphan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`bieuthuetoanphan` (
  `idBieuThueToanPhan` VARCHAR(255) NOT NULL,
  `thunhaptinhthue` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `thuesuat` DOUBLE NULL DEFAULT NULL,
  `cauhinh_idCauHinh` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idBieuThueToanPhan`),
  INDEX `fk_bieuthuetoanphan_cauhinh1_idx` (`cauhinh_idCauHinh` ASC) VISIBLE,
  CONSTRAINT `fk_bieuthuetoanphan_cauhinh1`
    FOREIGN KEY (`cauhinh_idCauHinh`)
    REFERENCES `thue_tncn`.`cauhinh` (`idCauHinh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`hoadondongthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`hoadondongthue` (
  `id` VARCHAR(255) NOT NULL,
  `kyquyettoan` VARCHAR(45) NULL DEFAULT NULL,
  `sotienphaidong` DOUBLE NULL DEFAULT NULL,
  `nguoinopthue_id` VARCHAR(45) NOT NULL,
  `tongcucthue_idTongCucThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hoadondongthue_nguoinopthue1_idx` (`nguoinopthue_id` ASC) VISIBLE,
  INDEX `fk_hoadondongthue_tongcucthue1_idx` (`tongcucthue_idTongCucThue` ASC) VISIBLE,
  CONSTRAINT `fk_hoadondongthue_nguoinopthue1`
    FOREIGN KEY (`nguoinopthue_id`)
    REFERENCES `thue_tncn`.`nguoinopthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hoadondongthue_tongcucthue1`
    FOREIGN KEY (`tongcucthue_idTongCucThue`)
    REFERENCES `thue_tncn`.`tongcucthue` (`idTongCucThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`nganhanghotrothanhtoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`nganhanghotrothanhtoan` (
  `id` VARCHAR(255) NOT NULL,
  `tennganhang` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`chitietgiaodichdongthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`chitietgiaodichdongthue` (
  `id` VARCHAR(255) NOT NULL,
  `phithanhtoan` DOUBLE NULL DEFAULT NULL,
  `hinhthucthanhtoan` VARCHAR(255) NULL DEFAULT NULL,
  `hoadondongthue_id` VARCHAR(255) NOT NULL,
  `nganhanghotrothanhtoan_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chitietgiaodichdongthue_hoadondongthue1_idx` (`hoadondongthue_id` ASC) VISIBLE,
  INDEX `fk_chitietgiaodichdongthue_nganhanghotrothanhtoan1_idx` (`nganhanghotrothanhtoan_id` ASC) VISIBLE,
  CONSTRAINT `fk_chitietgiaodichdongthue_hoadondongthue1`
    FOREIGN KEY (`hoadondongthue_id`)
    REFERENCES `thue_tncn`.`hoadondongthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chitietgiaodichdongthue_nganhanghotrothanhtoan1`
    FOREIGN KEY (`nganhanghotrothanhtoan_id`)
    REFERENCES `thue_tncn`.`nganhanghotrothanhtoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tokhaidanhchocanhankinhdoanh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tokhaidanhchocanhankinhdoanh` (
  `idToKhaiDanhChoCaNhanKinhDoanh` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idToKhaiDanhChoCaNhanKinhDoanh`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`hosodangkythue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`hosodangkythue` (
  `idHoSoDangKyThue` VARCHAR(255) NOT NULL,
  `magiaodich` VARCHAR(255) NULL DEFAULT NULL,
  `ngaynophoso` DATE NULL DEFAULT NULL,
  `trangthaihoso` VARCHAR(255) NULL DEFAULT NULL,
  `nguoinopthue_id` VARCHAR(45) NOT NULL,
  `tokhaidanhchocanhankinhdoanh_idToKhaiDanhChoCaNhanKinhDoanh` VARCHAR(255) NOT NULL,
  `tongcucthue_idTongCucThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idHoSoDangKyThue`),
  INDEX `fk_hosodangkythue_nguoinopthue1_idx` (`nguoinopthue_id` ASC) VISIBLE,
  INDEX `fk_hosodangkythue_tokhaidanhchocanhankinhdoanh1_idx` (`tokhaidanhchocanhankinhdoanh_idToKhaiDanhChoCaNhanKinhDoanh` ASC) VISIBLE,
  INDEX `fk_hosodangkythue_tongcucthue1_idx` (`tongcucthue_idTongCucThue` ASC) VISIBLE,
  CONSTRAINT `fk_hosodangkythue_nguoinopthue1`
    FOREIGN KEY (`nguoinopthue_id`)
    REFERENCES `thue_tncn`.`nguoinopthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hosodangkythue_tokhaidanhchocanhankinhdoanh1`
    FOREIGN KEY (`tokhaidanhchocanhankinhdoanh_idToKhaiDanhChoCaNhanKinhDoanh`)
    REFERENCES `thue_tncn`.`tokhaidanhchocanhankinhdoanh` (`idToKhaiDanhChoCaNhanKinhDoanh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hosodangkythue_tongcucthue1`
    FOREIGN KEY (`tongcucthue_idTongCucThue`)
    REFERENCES `thue_tncn`.`tongcucthue` (`idTongCucThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tokhaithuecanhanthongthuong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tokhaithuecanhanthongthuong` (
  `idToKhaiThueCaNhanThongThuong` VARCHAR(255) NOT NULL,
  `hosodangkythue_idHoSoDangKyThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idToKhaiThueCaNhanThongThuong`),
  INDEX `fk_tokhaithuecanhanthongthuong_hosodangkythue1_idx` (`hosodangkythue_idHoSoDangKyThue` ASC) VISIBLE,
  CONSTRAINT `fk_tokhaithuecanhanthongthuong_hosodangkythue1`
    FOREIGN KEY (`hosodangkythue_idHoSoDangKyThue`)
    REFERENCES `thue_tncn`.`hosodangkythue` (`idHoSoDangKyThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`diachi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`diachi` (
  `idDiaChi` VARCHAR(255) NOT NULL,
  `sonha` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tinh/TP` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `quan/huyen` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `xa/phuong` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `loaidiachi` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `dienthoai` VARCHAR(14) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tokhaithuecanhanthongthuong_idToKhaiThueCaNhanThongThuong` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idDiaChi`),
  INDEX `fk_diachi_tokhaithuecanhanthongthuong1_idx` (`tokhaithuecanhanthongthuong_idToKhaiThueCaNhanThongThuong` ASC) VISIBLE,
  CONSTRAINT `fk_diachi_tokhaithuecanhanthongthuong1`
    FOREIGN KEY (`tokhaithuecanhanthongthuong_idToKhaiThueCaNhanThongThuong`)
    REFERENCES `thue_tncn`.`tokhaithuecanhanthongthuong` (`idToKhaiThueCaNhanThongThuong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`giaytocanhan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`giaytocanhan` (
  `idGiayToCaNhan` VARCHAR(255) NOT NULL,
  `loaigiayto` VARCHAR(255) NULL DEFAULT NULL,
  `sogiayto` VARCHAR(255) NULL DEFAULT NULL,
  `ngaycap` DATE NULL DEFAULT NULL,
  `noicap` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `hotennguoidkythue` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `ngaysinh` DATE NULL DEFAULT NULL,
  `gioitinh` BIT(1) NULL DEFAULT NULL,
  `quoctich` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tokhaithuecanhanthongthuong_idToKhaiThueCaNhanThongThuong` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idGiayToCaNhan`),
  INDEX `fk_giaytocanhan_tokhaithuecanhanthongthuong1_idx` (`tokhaithuecanhanthongthuong_idToKhaiThueCaNhanThongThuong` ASC) VISIBLE,
  CONSTRAINT `fk_giaytocanhan_tokhaithuecanhanthongthuong1`
    FOREIGN KEY (`tokhaithuecanhanthongthuong_idToKhaiThueCaNhanThongThuong`)
    REFERENCES `thue_tncn`.`tokhaithuecanhanthongthuong` (`idToKhaiThueCaNhanThongThuong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`hosokhaibaothue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`hosokhaibaothue` (
  `id` VARCHAR(255) NOT NULL,
  `magiaodich` VARCHAR(255) NULL DEFAULT NULL,
  `ngaytaohoso` DATE NULL DEFAULT NULL,
  `trangthaihoso` VARCHAR(255) NULL DEFAULT NULL,
  `nguoinopthue_id` VARCHAR(45) NOT NULL,
  `tongcucthue_idTongCucThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hosokhaibaothue_nguoinopthue1_idx` (`nguoinopthue_id` ASC) VISIBLE,
  INDEX `fk_hosokhaibaothue_tongcucthue1_idx` (`tongcucthue_idTongCucThue` ASC) VISIBLE,
  CONSTRAINT `fk_hosokhaibaothue_nguoinopthue1`
    FOREIGN KEY (`nguoinopthue_id`)
    REFERENCES `thue_tncn`.`nguoinopthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hosokhaibaothue_tongcucthue1`
    FOREIGN KEY (`tongcucthue_idTongCucThue`)
    REFERENCES `thue_tncn`.`tongcucthue` (`idTongCucThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tokhaiquyettoanthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tokhaiquyettoanthue` (
  `idToKhaiQuyetToanThue` INT NOT NULL,
  `tennguoinopthue` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `masothue` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `quan/huyen` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tinh/TP` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `dienthoai` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idToKhaiQuyetToanThue`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`hosoquyettoanthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`hosoquyettoanthue` (
  `idHoSoQuyetToanThue` VARCHAR(255) NOT NULL,
  `magiaodich` VARCHAR(45) NULL DEFAULT NULL,
  `ngaynophoso` DATE NULL DEFAULT NULL,
  `trangthaihoso` VARCHAR(255) NULL DEFAULT NULL,
  `tennguoigui` VARCHAR(255) NULL DEFAULT NULL,
  `diachilienhe` VARCHAR(255) NULL DEFAULT NULL,
  `diachiemail` VARCHAR(255) NULL DEFAULT NULL,
  `loaitokhai` VARCHAR(255) NULL DEFAULT NULL,
  `coquanquyettoan` VARCHAR(255) NULL DEFAULT NULL,
  `truonghopquyettoanthue` VARCHAR(255) NULL DEFAULT NULL,
  `namkekhai` INT NULL DEFAULT NULL,
  `tuthang` INT NULL DEFAULT NULL,
  `denthang` INT NULL DEFAULT NULL,
  `nguoinopthue_id` VARCHAR(45) NOT NULL,
  `tokhaiquyettoanthue_idToKhaiQuyetToanThue` INT NOT NULL,
  `tongcucthue_idTongCucThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idHoSoQuyetToanThue`),
  INDEX `fk_hosoquyettoanthue_nguoinopthue1_idx` (`nguoinopthue_id` ASC) VISIBLE,
  INDEX `fk_hosoquyettoanthue_tokhaiquyettoanthue1_idx` (`tokhaiquyettoanthue_idToKhaiQuyetToanThue` ASC) VISIBLE,
  INDEX `fk_hosoquyettoanthue_tongcucthue1_idx` (`tongcucthue_idTongCucThue` ASC) VISIBLE,
  CONSTRAINT `fk_hosoquyettoanthue_nguoinopthue1`
    FOREIGN KEY (`nguoinopthue_id`)
    REFERENCES `thue_tncn`.`nguoinopthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hosoquyettoanthue_tokhaiquyettoanthue1`
    FOREIGN KEY (`tokhaiquyettoanthue_idToKhaiQuyetToanThue`)
    REFERENCES `thue_tncn`.`tokhaiquyettoanthue` (`idToKhaiQuyetToanThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hosoquyettoanthue_tongcucthue1`
    FOREIGN KEY (`tongcucthue_idTongCucThue`)
    REFERENCES `thue_tncn`.`tongcucthue` (`idTongCucThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhapkhongchiuthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhapkhongchiuthue` (
  `idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  `nguoinopthue_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idThuNhapKhongChiuThue`),
  INDEX `fk_thunhapkhongchiuthue_nguoinopthue1_idx` (`nguoinopthue_id` ASC) VISIBLE,
  CONSTRAINT `fk_thunhapkhongchiuthue_nguoinopthue1`
    FOREIGN KEY (`nguoinopthue_id`)
    REFERENCES `thue_tncn`.`nguoinopthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`luonghuuhangthang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`luonghuuhangthang` (
  `idLuongHuuHangThang` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `thunhapkhongchiuthue_idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idLuongHuuHangThang`),
  INDEX `fk_luonghuuhangthang_thunhapkhongchiuthue1_idx` (`thunhapkhongchiuthue_idThuNhapKhongChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_luonghuuhangthang_thunhapkhongchiuthue1`
    FOREIGN KEY (`thunhapkhongchiuthue_idThuNhapKhongChiuThue`)
    REFERENCES `thue_tncn`.`thunhapkhongchiuthue` (`idThuNhapKhongChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tokhaithue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tokhaithue` (
  `idToKhaiThue` VARCHAR(255) NOT NULL,
  `hosokhaibaothue_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idToKhaiThue`),
  INDEX `fk_tokhaithue_hosokhaibaothue1_idx` (`hosokhaibaothue_id` ASC) VISIBLE,
  CONSTRAINT `fk_tokhaithue_hosokhaibaothue1`
    FOREIGN KEY (`hosokhaibaothue_id`)
    REFERENCES `thue_tncn`.`hosokhaibaothue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`mauso02/kk-tncn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`mauso02/kk-tncn` (
  `idMauSo02/KK-TNCN` VARCHAR(255) NOT NULL,
  `tokhaithue_idToKhaiThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMauSo02/KK-TNCN`),
  INDEX `fk_mauso02/kk-tncn_tokhaithue1_idx` (`tokhaithue_idToKhaiThue` ASC) VISIBLE,
  CONSTRAINT `fk_mauso02/kk-tncn_tokhaithue1`
    FOREIGN KEY (`tokhaithue_idToKhaiThue`)
    REFERENCES `thue_tncn`.`tokhaithue` (`idToKhaiThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`mauso04/cnv-tncn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`mauso04/cnv-tncn` (
  `idMauSo04/CNV-TNCN` VARCHAR(255) NOT NULL,
  `tokhaithue_idToKhaiThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMauSo04/CNV-TNCN`),
  INDEX `fk_mauso04/cnv-tncn_tokhaithue1_idx` (`tokhaithue_idToKhaiThue` ASC) VISIBLE,
  CONSTRAINT `fk_mauso04/cnv-tncn_tokhaithue1`
    FOREIGN KEY (`tokhaithue_idToKhaiThue`)
    REFERENCES `thue_tncn`.`tokhaithue` (`idToKhaiThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`mauso04/nng-tncn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`mauso04/nng-tncn` (
  `idMauSo04/NNG-TNCN` VARCHAR(255) NOT NULL,
  `tokhaithue_idToKhaiThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMauSo04/NNG-TNCN`),
  INDEX `fk_mauso04/nng-tncn_tokhaithue1_idx` (`tokhaithue_idToKhaiThue` ASC) VISIBLE,
  CONSTRAINT `fk_mauso04/nng-tncn_tokhaithue1`
    FOREIGN KEY (`tokhaithue_idToKhaiThue`)
    REFERENCES `thue_tncn`.`tokhaithue` (`idToKhaiThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`mauso04/tkqt-tncn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`mauso04/tkqt-tncn` (
  `idMauSo04/TKQT-TNCN` VARCHAR(255) NOT NULL,
  `MauSo04/TKQT-TNCNcol` VARCHAR(255) NULL DEFAULT NULL,
  `tokhaithue_idToKhaiThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMauSo04/TKQT-TNCN`),
  INDEX `fk_mauso04/tkqt-tncn_tokhaithue1_idx` (`tokhaithue_idToKhaiThue` ASC) VISIBLE,
  CONSTRAINT `fk_mauso04/tkqt-tncn_tokhaithue1`
    FOREIGN KEY (`tokhaithue_idToKhaiThue`)
    REFERENCES `thue_tncn`.`tokhaithue` (`idToKhaiThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`mauso04/đtv-tncn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`mauso04/đtv-tncn` (
  `idMauSo04/ĐTV-TNCN` VARCHAR(255) NOT NULL,
  `tokhaithue_idToKhaiThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMauSo04/ĐTV-TNCN`),
  INDEX `fk_mauso04/đtv-tncn_tokhaithue1_idx` (`tokhaithue_idToKhaiThue` ASC) VISIBLE,
  CONSTRAINT `fk_mauso04/đtv-tncn_tokhaithue1`
    FOREIGN KEY (`tokhaithue_idToKhaiThue`)
    REFERENCES `thue_tncn`.`tokhaithue` (`idToKhaiThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`mauso06/tncn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`mauso06/tncn` (
  `idMauSo06/TNCN` VARCHAR(255) NOT NULL,
  `tokhaithue_idToKhaiThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMauSo06/TNCN`),
  INDEX `fk_mauso06/tncn_tokhaithue1_idx` (`tokhaithue_idToKhaiThue` ASC) VISIBLE,
  CONSTRAINT `fk_mauso06/tncn_tokhaithue1`
    FOREIGN KEY (`tokhaithue_idToKhaiThue`)
    REFERENCES `thue_tncn`.`tokhaithue` (`idToKhaiThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thongtingiaykhaisinh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thongtingiaykhaisinh` (
  `id` VARCHAR(255) NOT NULL,
  `so` VARCHAR(45) NULL DEFAULT NULL,
  `quyenso` VARCHAR(45) NULL DEFAULT NULL,
  `quocgia` VARCHAR(255) NULL DEFAULT NULL,
  `tinh/TP` VARCHAR(255) NULL DEFAULT NULL,
  `quan/huyen` VARCHAR(255) NULL DEFAULT NULL,
  `phuong/xa` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`nguoiphuthuoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`nguoiphuthuoc` (
  `id` VARCHAR(255) NOT NULL,
  `hoten` VARCHAR(255) NULL DEFAULT NULL,
  `ngaysinh` DATE NULL DEFAULT NULL,
  `masothue` VARCHAR(255) NULL DEFAULT NULL,
  `quoctich` VARCHAR(255) NULL DEFAULT NULL,
  `cccd` VARCHAR(12) NULL DEFAULT NULL,
  `cmnd` VARCHAR(12) NULL DEFAULT NULL,
  `sodinhdangcanhan` VARCHAR(255) NULL DEFAULT NULL,
  `thoigiangiamtrututhang` DATE NULL DEFAULT NULL,
  `thoigiangiamtrudenthang` DATE NULL DEFAULT NULL,
  `fkNPT_DKY_GIAMTRU` VARCHAR(255) NOT NULL,
  `fkNPT_GIAYKHAISINH` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkNPT_DKY_GIAMTRU` (`fkNPT_DKY_GIAMTRU` ASC) INVISIBLE,
  INDEX `fkNPT_GIAYKHAISINH` (`fkNPT_GIAYKHAISINH` ASC) VISIBLE,
  CONSTRAINT `fkNPT_DKY_GIAMTRU`
    FOREIGN KEY (`fkNPT_DKY_GIAMTRU`)
    REFERENCES `thue_tncn`.`bangtonghopnguoiphuthuocdkygiamtrugiacanh` (`idBangTongHopNguoiPhuThuocDKYGiamTruGiaCanh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkNPT_GIAYKHAISINH`
    FOREIGN KEY (`fkNPT_GIAYKHAISINH`)
    REFERENCES `thue_tncn`.`thongtingiaykhaisinh` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`taikhoanthanhtoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`taikhoanthanhtoan` (
  `id` VARCHAR(255) NOT NULL,
  `hotenchuthe` VARCHAR(255) NULL DEFAULT NULL,
  `ngayhieuluc` DATE NULL DEFAULT NULL,
  `sothe` VARCHAR(45) NULL DEFAULT NULL,
  `nguoinopthue_id` VARCHAR(45) NOT NULL,
  `nganhanghotrothanhtoan_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_taikhoanthanhtoan_nguoinopthue1_idx` (`nguoinopthue_id` ASC) VISIBLE,
  INDEX `fk_taikhoanthanhtoan_nganhanghotrothanhtoan1_idx` (`nganhanghotrothanhtoan_id` ASC) VISIBLE,
  CONSTRAINT `fk_taikhoanthanhtoan_nguoinopthue1`
    FOREIGN KEY (`nguoinopthue_id`)
    REFERENCES `thue_tncn`.`nguoinopthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taikhoanthanhtoan_nganhanghotrothanhtoan1`
    FOREIGN KEY (`nganhanghotrothanhtoan_id`)
    REFERENCES `thue_tncn`.`nganhanghotrothanhtoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhapchiuthue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhapchiuthue` (
  `idThuNhapChiuThue` VARCHAR(255) NOT NULL,
  `nguoinopthue_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idThuNhapChiuThue`),
  INDEX `fk_thunhapchiuthue_nguoinopthue1_idx` (`nguoinopthue_id` ASC) VISIBLE,
  CONSTRAINT `fk_thunhapchiuthue_nguoinopthue1`
    FOREIGN KEY (`nguoinopthue_id`)
    REFERENCES `thue_tncn`.`nguoinopthue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptrungthuongtrongcasino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptrungthuongtrongcasino` (
  `idThuNhapTrungThuongTrongCasino` VARCHAR(255) NOT NULL,
  `thunhapkhongchiuthue_idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTrungThuongTrongCasino`),
  INDEX `fk_thunhaptrungthuongtrongcasino_thunhapkhongchiuthue1_idx` (`thunhapkhongchiuthue_idThuNhapKhongChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptrungthuongtrongcasino_thunhapkhongchiuthue1`
    FOREIGN KEY (`thunhapkhongchiuthue_idThuNhapKhongChiuThue`)
    REFERENCES `thue_tncn`.`thunhapkhongchiuthue` (`idThuNhapKhongChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptubanquyennhuongquyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptubanquyennhuongquyen` (
  `idThuNhapTuBanQuyenNhuongQuyen` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `thunhapchiuthue_idThuNhapChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTuBanQuyenNhuongQuyen`),
  INDEX `fk_thunhaptubanquyennhuongquyen_thunhapchiuthue1_idx` (`thunhapchiuthue_idThuNhapChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptubanquyennhuongquyen_thunhapchiuthue1`
    FOREIGN KEY (`thunhapchiuthue_idThuNhapChiuThue`)
    REFERENCES `thue_tncn`.`thunhapchiuthue` (`idThuNhapChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptuchuyennhuongbatdongsan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptuchuyennhuongbatdongsan` (
  `idThuNhapTuChuyenNhuongBatDongSan` VARCHAR(255) NOT NULL,
  `thunhapchiuthue_idThuNhapChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTuChuyenNhuongBatDongSan`),
  INDEX `fk_thunhaptuviecchuyennhuongbatdongsan_thunhapchiuthue1_idx` (`thunhapchiuthue_idThuNhapChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptuviecchuyennhuongbatdongsan_thunhapchiuthue1`
    FOREIGN KEY (`thunhapchiuthue_idThuNhapChiuThue`)
    REFERENCES `thue_tncn`.`thunhapchiuthue` (`idThuNhapChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptudautuvon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptudautuvon` (
  `idThuNhapTuDauTuVon` VARCHAR(255) NOT NULL,
  `thunhapchiuthue_idThuNhapChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTuDauTuVon`, `thunhapchiuthue_idThuNhapChiuThue`),
  INDEX `fk_thunhaptudautuvon_thunhapchiuthue_idx` (`thunhapchiuthue_idThuNhapChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptudautuvon_thunhapchiuthue`
    FOREIGN KEY (`thunhapchiuthue_idThuNhapChiuThue`)
    REFERENCES `thue_tncn`.`thunhapchiuthue` (`idThuNhapChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptukinhdoanh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptukinhdoanh` (
  `idThuNhapTuKinhDoanh` VARCHAR(255) NOT NULL,
  `thunhapchiuthue_idThuNhapChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTuKinhDoanh`),
  INDEX `fk_thunhaptukinhdoanh_thunhapchiuthue1_idx` (`thunhapchiuthue_idThuNhapChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptukinhdoanh_thunhapchiuthue1`
    FOREIGN KEY (`thunhapchiuthue_idThuNhapChiuThue`)
    REFERENCES `thue_tncn`.`thunhapchiuthue` (`idThuNhapChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptuthuaketren10tr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptuthuaketren10tr` (
  `idThuNhapTuThuaKeTren10Tr` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `thunhapchiuthue_idThuNhapChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTuThuaKeTren10Tr`),
  INDEX `fk_thunhaptuthuaketren10tr_thunhapchiuthue1_idx` (`thunhapchiuthue_idThuNhapChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptuthuaketren10tr_thunhapchiuthue1`
    FOREIGN KEY (`thunhapchiuthue_idThuNhapChiuThue`)
    REFERENCES `thue_tncn`.`thunhapchiuthue` (`idThuNhapChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptutienluongtiencong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptutienluongtiencong` (
  `idThuNhapTuTienLuongTienCong` VARCHAR(255) NOT NULL,
  `thunhapchiuthue_idThuNhapChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTuTienLuongTienCong`),
  INDEX `fk_thunhaptutienluongtiencong_thunhapchiuthue1_idx` (`thunhapchiuthue_idThuNhapChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptutienluongtiencong_thunhapchiuthue1`
    FOREIGN KEY (`thunhapchiuthue_idThuNhapChiuThue`)
    REFERENCES `thue_tncn`.`thunhapchiuthue` (`idThuNhapChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptutrungthuongquatang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptutrungthuongquatang` (
  `idThuNhapTuTrungThuongQuaTang` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `thunhapchiuthue_idThuNhapChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTuTrungThuongQuaTang`),
  INDEX `fk_thunhaptutrungthuongquatang_thunhapchiuthue1_idx` (`thunhapchiuthue_idThuNhapChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptutrungthuongquatang_thunhapchiuthue1`
    FOREIGN KEY (`thunhapchiuthue_idThuNhapChiuThue`)
    REFERENCES `thue_tncn`.`thunhapchiuthue` (`idThuNhapChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`thunhaptuvantaiduongbienquocte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`thunhaptuvantaiduongbienquocte` (
  `idThuNhapTuVanTaiDuongBienQuocTe` VARCHAR(255) NOT NULL,
  `thunhapkhongchiuthue_idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idThuNhapTuVanTaiDuongBienQuocTe`),
  INDEX `fk_thunhaptuvantaiduongbienquocte_thunhapkhongchiuthue1_idx` (`thunhapkhongchiuthue_idThuNhapKhongChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_thunhaptuvantaiduongbienquocte_thunhapkhongchiuthue1`
    FOREIGN KEY (`thunhapkhongchiuthue_idThuNhapKhongChiuThue`)
    REFERENCES `thue_tncn`.`thunhapkhongchiuthue` (`idThuNhapKhongChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tienboithuongbaohiemnhantho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tienboithuongbaohiemnhantho` (
  `idTienBoiThuongBaoHiemNhanTho` VARCHAR(255) NOT NULL,
  `thunhapkhongchiuthue_idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTienBoiThuongBaoHiemNhanTho`),
  INDEX `fk_tienboithuongbaohiemnhantho_thunhapkhongchiuthue1_idx` (`thunhapkhongchiuthue_idThuNhapKhongChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_tienboithuongbaohiemnhantho_thunhapkhongchiuthue1`
    FOREIGN KEY (`thunhapkhongchiuthue_idThuNhapKhongChiuThue`)
    REFERENCES `thue_tncn`.`thunhapkhongchiuthue` (`idThuNhapKhongChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tienlaitunganhangbaohiemnhantho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tienlaitunganhangbaohiemnhantho` (
  `idTienLaiTuNganHangBaoHiemNhanTho` VARCHAR(255) NOT NULL,
  `thunhapkhongchiuthue_idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTienLaiTuNganHangBaoHiemNhanTho`),
  INDEX `fk_tienlaitunganhangbaohiemnhantho_thunhapkhongchiuthue1_idx` (`thunhapkhongchiuthue_idThuNhapKhongChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_tienlaitunganhangbaohiemnhantho_thunhapkhongchiuthue1`
    FOREIGN KEY (`thunhapkhongchiuthue_idThuNhapKhongChiuThue`)
    REFERENCES `thue_tncn`.`thunhapkhongchiuthue` (`idThuNhapKhongChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tienluonghuudongbaohiemtunguyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tienluonghuudongbaohiemtunguyen` (
  `idTienLuongHuuDongBaoHiemTuNguyen` VARCHAR(255) NOT NULL,
  `thunhapkhongchiuthue_idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTienLuongHuuDongBaoHiemTuNguyen`),
  INDEX `fk_tienluonghuudongbaohiemtunguyen_thunhapkhongchiuthue1_idx` (`thunhapkhongchiuthue_idThuNhapKhongChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_tienluonghuudongbaohiemtunguyen_thunhapkhongchiuthue1`
    FOREIGN KEY (`thunhapkhongchiuthue_idThuNhapKhongChiuThue`)
    REFERENCES `thue_tncn`.`thunhapkhongchiuthue` (`idThuNhapKhongChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tienthuakequatangtructiep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tienthuakequatangtructiep` (
  `idTienThuaKeQuaTangTrucTiep` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `TienThuaKeQuaTangTrucTiepcol` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `thunhapkhongchiuthue_idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTienThuaKeQuaTangTrucTiep`),
  INDEX `fk_tienthuakequatangtructiep_thunhapkhongchiuthue1_idx` (`thunhapkhongchiuthue_idThuNhapKhongChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_tienthuakequatangtructiep_thunhapkhongchiuthue1`
    FOREIGN KEY (`thunhapkhongchiuthue_idThuNhapKhongChiuThue`)
    REFERENCES `thue_tncn`.`thunhapkhongchiuthue` (`idThuNhapKhongChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `thue_tncn`.`tntuchuyennhuongbdstronggiadinh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thue_tncn`.`tntuchuyennhuongbdstronggiadinh` (
  `idTNTuChuyenNhuongBDSTrongGiaDinh` VARCHAR(255) NOT NULL,
  `thunhapkhongchiuthue_idThuNhapKhongChiuThue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTNTuChuyenNhuongBDSTrongGiaDinh`),
  INDEX `fk_tntuchuyennhuongbdstronggiadinh_thunhapkhongchiuthue1_idx` (`thunhapkhongchiuthue_idThuNhapKhongChiuThue` ASC) VISIBLE,
  CONSTRAINT `fk_tntuchuyennhuongbdstronggiadinh_thunhapkhongchiuthue1`
    FOREIGN KEY (`thunhapkhongchiuthue_idThuNhapKhongChiuThue`)
    REFERENCES `thue_tncn`.`thunhapkhongchiuthue` (`idThuNhapKhongChiuThue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
